# -*- coding: utf-8 -*-
"""DeepLearning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BsdyHX5EZTP4loeLC6CJvRuPHFOziVNo
"""

class MultiHeadSelfAttention(layers.Layer):
    def __init__(self, embed_dim, num_heads=4, dropout=0.1, **kwargs):
        super().__init__(**kwargs)
        self.embed_dim = embed_dim
        self.num_heads = num_heads
        assert embed_dim % num_heads == 0
        self.projection_dim = embed_dim // num_heads
        self.query_dense = layers.Dense(embed_dim)
        self.key_dense   = layers.Dense(embed_dim)
        self.value_dense = layers.Dense(embed_dim)
        self.combine_heads = layers.Dense(embed_dim)
        self.dropout = layers.Dropout(dropout)

    def attention(self, query, key, value):
        score = tf.matmul(query, key, transpose_b=True)
        dim_key = tf.cast(tf.shape(key)[-1], tf.float32)
        scaled_score = score / tf.math.sqrt(dim_key)
        weights = tf.nn.softmax(scaled_score, axis=-1)
        weights = self.dropout(weights)
        return tf.matmul(weights, value)

    def separate_heads(self, x, batch_size):
        x = tf.reshape(x, (batch_size, -1, self.num_heads, self.projection_dim))
        return tf.transpose(x, perm=[0, 2, 1, 3])

    def call(self, inputs, training=False):
        batch_size = tf.shape(inputs)[0]
        query = self.separate_heads(self.query_dense(inputs), batch_size)
        key   = self.separate_heads(self.key_dense(inputs),   batch_size)
        value = self.separate_heads(self.value_dense(inputs), batch_size)
        attention = self.attention(query, key, value)
        attention = tf.transpose(attention, perm=[0, 2, 1, 3])
        concat = tf.reshape(attention, (batch_size, -1, self.embed_dim))
        return self.combine_heads(concat)

def build_ar_ncf(num_users, num_items, embed_dim=64, mlp_layers=[128, 64, 32],
                 num_heads=4, dropout=0.2, l2_reg=1e-6, name="AR_NCF"):
    # Inputs
    user_input = layers.Input(shape=(), name="user_id", dtype=tf.int32)
    item_input = layers.Input(shape=(), name="item_id", dtype=tf.int32)

    # Embeddings
    user_emb = layers.Embedding(
        num_users, embed_dim,
        embeddings_regularizer=regularizers.l2(l2_reg),
        name="user_embedding"
    )(user_input)
    item_emb = layers.Embedding(
        num_items, embed_dim,
        embeddings_regularizer=regularizers.l2(l2_reg),
        name="item_embedding"
    )(item_input)

    user_vec = layers.Flatten()(user_emb)
    item_vec = layers.Flatten()(item_emb)

    # ----- GMF path -----
    gmf = layers.Multiply(name="gmf_product")([user_vec, item_vec])

    # ----- MLP + Attention path -----
    mlp_input = layers.Concatenate(name="mlp_concat")([user_vec, item_vec])
    x = mlp_input
    for i, units in enumerate(mlp_layers):
        x = layers.Dense(units, activation="relu",
                         kernel_regularizer=regularizers.l2(l2_reg),
                         name=f"mlp_{i}")(x)
        x = layers.Dropout(dropout)(x)

    # Expand for attention: treat as sequence of length 1 (or you can stack more features)
    x_attn = layers.Reshape((1, mlp_layers[-1]))(x)
    attn_out = MultiHeadSelfAttention(mlp_layers[-1], num_heads=num_heads,
                                      dropout=dropout, name="mhsa")(x_attn)
    attn_out = layers.Flatten()(attn_out)

    # Residual connection
    residual = layers.Dense(mlp_layers[-1], name="residual_proj")(x)
    attn_res = layers.Add(name="residual_add")([attn_out, residual])
    attn_res = layers.Reshape((32,))(attn_res)
    attn_res = layers.LayerNormalization(axis=-1, name="attn_ln")(attn_res)

    # ----- Fusion -----
    fusion = layers.Concatenate(name="fusion")([gmf, attn_res])
    fusion = layers.Dense(64, activation="relu",
                          kernel_regularizer=regularizers.l2(l2_reg))(fusion)
    fusion = layers.Dropout(dropout)(fusion)
    fusion = layers.Dense(32, activation="relu")(fusion)

    # Output (explicit rating prediction)
    rating = layers.Dense(1, activation="linear", name="rating")(fusion)
    return Model(inputs=[user_input, item_input], outputs=rating, name=name)


# Model instantiation
model = build_ar_ncf(num_users=70000, num_items=12000,
                     embed_dim=64, mlp_layers=[128,64,32],
                     num_heads=4, dropout=0.2, l2_reg=1e-6)

# Print structure
model.summary()
model = build_ar_ncf(num_users=70000, num_items=12000)
# Save model
model.save("my_model.keras")

# Install netron（Only once）
!pip install netron
import netron
netron.start("ar_ncf_temp.h5")
